"use client";

import { FormEvent, useState } from "react";

type AcademicPath = { id: string; title: string; description: string; startYear: number; endYear?: number | null; inProgress: boolean; subjects: string[]; order: number };
type PathForm = { title: string; description: string; startYear: string; endYear: string; inProgress: boolean; subjects: string; order: string };
const emptyForm: PathForm = { title: "", description: "", startYear: "", endYear: "", inProgress: false, subjects: "", order: "0" };

export function AcademicPathManager({ initialPath }: { initialPath: AcademicPath[] }) {
  const [path, setPath] = useState(initialPath); const [form, setForm] = useState(emptyForm); const [editing, setEditing] = useState<string | null>(null); const [feedback, setFeedback] = useState("");
  const set = (key: keyof PathForm, value: string | boolean) => setForm((current) => ({ ...current, [key]: value }));
  function edit(item: AcademicPath) { setEditing(item.id); setForm({ title: item.title, description: item.description, startYear: String(item.startYear), endYear: item.endYear ? String(item.endYear) : "", inProgress: item.inProgress, subjects: item.subjects.join(", "), order: String(item.order) }); window.scrollTo({ top: 0, behavior: "smooth" }); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setFeedback("Enregistrement…"); const payload = { title: form.title, description: form.description, startYear: Number(form.startYear), endYear: form.inProgress || !form.endYear ? null : Number(form.endYear), inProgress: form.inProgress, subjects: form.subjects.split(",").map((item) => item.trim()).filter(Boolean), order: Number(form.order) }; const response = await fetch(editing ? `/api/admin/academic-path/${editing}` : "/api/admin/academic-path", { method: editing ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json().catch(() => ({})); if (!response.ok) { setFeedback(data.message ?? "Impossible d’enregistrer cette étape."); return; } setPath((current) => editing ? current.map((item) => item.id === data.id ? data : item) : [...current, data].sort((a, b) => a.order - b.order)); setForm(emptyForm); setEditing(null); setFeedback("Étape enregistrée."); }
  async function remove(id: string) { if (!window.confirm("Supprimer cette étape du parcours ?")) return; const response = await fetch(`/api/admin/academic-path/${id}`, { method: "DELETE" }); if (response.ok) setPath((current) => current.filter((item) => item.id !== id)); else setFeedback("Suppression impossible."); }
  return <div className="admin-manager"><form className="admin-form" onSubmit={submit}><div className="admin-form-heading"><p className="eyebrow">{editing ? "Modifier l’étape" : "Nouvelle étape"}</p>{editing && <button type="button" className="quiet-button" onClick={() => { setEditing(null); setForm(emptyForm); }}>Annuler</button>}</div><div className="admin-form-grid"><label>Titre<input required value={form.title} onChange={(event) => set("title", event.target.value)} placeholder="Licence 1 — Informatique" /></label><label>Année de début<input required type="number" value={form.startYear} onChange={(event) => set("startYear", event.target.value)} /></label><label className="wide-field">Description<textarea required rows={4} value={form.description} onChange={(event) => set("description", event.target.value)} /></label><label>Année de fin<input type="number" disabled={form.inProgress} value={form.endYear} onChange={(event) => set("endYear", event.target.value)} /></label><label>Ordre d’affichage<input type="number" value={form.order} onChange={(event) => set("order", event.target.value)} /></label><label className="checkbox-field"><input type="checkbox" checked={form.inProgress} onChange={(event) => set("inProgress", event.target.checked)} /> Formation en cours</label><label className="wide-field">Matières <span className="field-hint">séparées par des virgules</span><input value={form.subjects} onChange={(event) => set("subjects", event.target.value)} placeholder="Algorithmique, Programmation, Réseaux" /></label></div><button type="submit">{editing ? "Mettre à jour" : "Ajouter l’étape"} →</button>{feedback && <p className="form-feedback">{feedback}</p>}</form><section className="admin-table"><div className="admin-form-heading"><p className="eyebrow">Parcours existant</p><span>{path.length}</span></div>{[...path].sort((a, b) => a.order - b.order).map((item) => <div className="admin-table-row" key={item.id}><div><strong>{item.title}</strong><span>{item.startYear} — {item.inProgress ? "En cours" : item.endYear} · ordre {item.order}</span></div><div><button className="quiet-button" type="button" onClick={() => edit(item)}>Modifier</button><button className="danger-button" type="button" onClick={() => remove(item.id)}>Supprimer</button></div></div>)}</section></div>;
}
