"use client";

import { FormEvent, useState } from "react";
import type { Project } from "@/lib/portfolio-data";

type ProjectForm = { name: string; slug: string; description: string; category: string; status: string; demoUrl: string; codeUrl: string; featured: boolean; order: string };
const emptyForm: ProjectForm = { name: "", slug: "", description: "", category: "FULLSTACK", status: "EN_COURS", demoUrl: "", codeUrl: "", featured: false, order: "0" };

export function ProjectManager({ initialProjects }: { initialProjects: Project[] }) {
  const [projects, setProjects] = useState(initialProjects);
  const [form, setForm] = useState<ProjectForm>(emptyForm);
  const [editing, setEditing] = useState<string | null>(null);
  const [feedback, setFeedback] = useState("");

  function edit(project: Project) { setEditing(project.id); setForm({ name: project.name, slug: project.slug, description: project.description, category: project.category, status: project.status, demoUrl: project.demoUrl ?? "", codeUrl: project.codeUrl ?? "", featured: false, order: "0" }); window.scrollTo({ top: 0, behavior: "smooth" }); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setFeedback("Enregistrement…"); const url = editing ? `/api/admin/projects/${editing}` : "/api/admin/projects"; const response = await fetch(url, { method: editing ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, order: Number(form.order), demoUrl: form.demoUrl || undefined, codeUrl: form.codeUrl || undefined }) }); const data = await response.json().catch(() => ({})); if (!response.ok) { setFeedback(data.message ?? "Impossible d’enregistrer le projet."); return; } setProjects((current) => editing ? current.map((item) => item.id === data.id ? data : item) : [...current, data]); setForm(emptyForm); setEditing(null); setFeedback("Projet enregistré."); }
  async function remove(id: string) { if (!window.confirm("Supprimer ce projet ?")) return; const response = await fetch(`/api/admin/projects/${id}`, { method: "DELETE" }); if (response.ok) setProjects((current) => current.filter((item) => item.id !== id)); else setFeedback("Suppression impossible."); }
  const set = (key: keyof ProjectForm, value: string | boolean) => setForm((current) => ({ ...current, [key]: value }));
  return <div className="admin-manager"><form className="admin-form" onSubmit={submit}><div className="admin-form-heading"><p className="eyebrow">{editing ? "Modifier" : "Nouveau projet"}</p>{editing && <button type="button" className="quiet-button" onClick={() => { setEditing(null); setForm(emptyForm); }}>Annuler</button>}</div><div className="admin-form-grid"><label>Nom<input required value={form.name} onChange={(event) => set("name", event.target.value)} /></label><label>Slug<input required value={form.slug} onChange={(event) => set("slug", event.target.value)} /></label><label className="wide-field">Description<textarea required rows={4} value={form.description} onChange={(event) => set("description", event.target.value)} /></label><label>Catégorie<select value={form.category} onChange={(event) => set("category", event.target.value)}><option value="FULLSTACK">Full-stack</option><option value="WEB_APP">Web app</option><option value="FRONTEND">Frontend</option><option value="BACKEND">Backend</option></select></label><label>Statut<select value={form.status} onChange={(event) => set("status", event.target.value)}><option value="EN_COURS">En cours</option><option value="TERMINE">Terminé</option><option value="EN_PAUSE">En pause</option><option value="ARCHIVE">Archivé</option></select></label><label>Démo<input type="url" value={form.demoUrl} onChange={(event) => set("demoUrl", event.target.value)} /></label><label>Code<input type="url" value={form.codeUrl} onChange={(event) => set("codeUrl", event.target.value)} /></label></div><button type="submit">{editing ? "Mettre à jour" : "Créer le projet"} →</button>{feedback && <p className="form-feedback">{feedback}</p>}</form><section className="admin-table"><div className="admin-form-heading"><p className="eyebrow">Projets existants</p><span>{projects.length}</span></div>{projects.map((project) => <div className="admin-table-row" key={project.id}><div><strong>{project.name}</strong><span>{project.status} · {project.category}</span></div><div><button className="quiet-button" type="button" onClick={() => edit(project)}>Modifier</button><button className="danger-button" type="button" onClick={() => remove(project.id)}>Supprimer</button></div></div>)}</section></div>;
}
