"use client";

import { FormEvent, useState } from "react";
import { ConfirmDialog } from "@/components/admin/confirm-dialog";

type Technology = { id: string; name: string; slug: string; description: string; icon?: string | null; category: string; featured?: boolean; order?: number };
type TechnologyForm = Omit<Technology, "id">;
const emptyForm: TechnologyForm = { name: "", slug: "", description: "", icon: "", category: "FRONTEND", featured: false, order: 0 };
const categories = [["FRONTEND", "Frontend"], ["BACKEND", "Backend"], ["BASE_DE_DONNEES", "Base de données"], ["OUTILS_DEVOPS", "Outils / DevOps"], ["METHODOLOGIES", "Méthodologies"], ["AUTRES", "Autres"]];

export function TechnologyManager({ initialTechnologies }: { initialTechnologies: Technology[] }) {
  const [technologies, setTechnologies] = useState(initialTechnologies); const [form, setForm] = useState(emptyForm); const [editing, setEditing] = useState<string | null>(null); const [feedback, setFeedback] = useState(""); const [deleteId, setDeleteId] = useState<string | null>(null);
  const set = (key: keyof TechnologyForm, value: string | boolean | number) => setForm((current) => ({ ...current, [key]: value }));
  function edit(item: Technology) { setEditing(item.id); setForm({ name: item.name, slug: item.slug, description: item.description, icon: item.icon ?? "", category: item.category, featured: item.featured ?? false, order: item.order ?? 0 }); window.scrollTo({ top: 0, behavior: "smooth" }); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setFeedback("Enregistrement…"); const response = await fetch(editing ? `/api/admin/technologies/${editing}` : "/api/admin/technologies", { method: editing ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, icon: form.icon || undefined, order: Number(form.order) }) }); const data = await response.json().catch(() => ({})); if (!response.ok) { setFeedback(data.message ?? "Impossible d’enregistrer la technologie."); return; } setTechnologies((current) => editing ? current.map((item) => item.id === data.id ? data : item) : [...current, data]); setForm(emptyForm); setEditing(null); setFeedback("Technologie enregistrée."); }
  async function remove() { if (!deleteId) return; const response = await fetch(`/api/admin/technologies/${deleteId}`, { method: "DELETE" }); if (response.ok) setTechnologies((current) => current.filter((item) => item.id !== deleteId)); else setFeedback("Suppression impossible."); setDeleteId(null); }
  return <div className="admin-manager"><ConfirmDialog open={Boolean(deleteId)} title="Supprimer cette technologie ?" description="Les projets associés peuvent être concernés par cette suppression." onCancel={() => setDeleteId(null)} onConfirm={remove} /><form className="admin-form" onSubmit={submit}><div className="admin-form-heading"><p className="eyebrow">{editing ? "Modifier la technologie" : "Nouvelle technologie"}</p>{editing && <button type="button" className="quiet-button" onClick={() => { setEditing(null); setForm(emptyForm); }}>Annuler</button>}</div><div className="admin-form-grid"><label>Nom<input required value={form.name} onChange={(event) => set("name", event.target.value)} /></label><label>Slug<input required value={form.slug} onChange={(event) => set("slug", event.target.value)} /></label><label className="wide-field">Description<textarea required rows={4} value={form.description} onChange={(event) => set("description", event.target.value)} /></label><label>Catégorie<select value={form.category} onChange={(event) => set("category", event.target.value)}>{categories.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>Icône ou slug d’icône<input value={form.icon ?? ""} onChange={(event) => set("icon", event.target.value)} placeholder="react" /></label><label>Ordre d’affichage<input type="number" min="0" value={form.order} onChange={(event) => set("order", Number(event.target.value))} /></label><label className="checkbox-field"><input type="checkbox" checked={Boolean(form.featured)} onChange={(event) => set("featured", event.target.checked)} /> Afficher sur l’accueil</label></div><button type="submit">{editing ? "Mettre à jour" : "Créer la technologie"} →</button>{feedback && <p className="form-feedback">{feedback}</p>}</form><section className="admin-table"><div className="admin-form-heading"><p className="eyebrow">Technologies existantes</p><span>{technologies.length}</span></div>{technologies.map((item) => <div className="admin-table-row" key={item.id}><div><strong>{item.name}</strong><span>{item.category} · {item.featured ? `Accueil · ordre ${item.order ?? 0}` : "Non affichée sur l’accueil"}</span></div><div><button className="quiet-button" type="button" onClick={() => edit(item)}>Modifier</button><button className="danger-button" type="button" onClick={() => setDeleteId(item.id)}>Supprimer</button></div></div>)}</section></div>;
}
